### ISSUE TITLE
[Readme] Add Youtube recording of DockerCon presentation to readme

### ISSUE THREAD

**Issue by leecalcote** [layer5io/image-hub#11]
**Current State:**
Missing video.

**Desired State:**
This talk, deck, and link (with appropriate playlist): https://www.youtube.com/watch?v=5BrbbKZOctw&list=PL3A-A6hPO2IN_HSU0pSfijBboiHggs5mC&index=4&t=0s should be added to:

- [ ] image-hub
- [ ] layer5.io/meshery
- [ ] docs.meshery.io

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Vineet-Sharma29** [comment]
@leecalcote I have added youtube link in readme in `image-hub`. Updated README.md of `meshery` repo with `docker-con-2020` links and updated docs in `overview.md`. Should I add links anywhere else?

**Comment by leecalcote** [comment]
It would be good to include a little no to the talk/event as well - https://docker.events.cube365.net/docker/dockercon/content/Videos/63TCCNpzDC7Xxnm8b

**Comment by Vineet-Sharma29** [comment]
@leecalcote Event link is present in readme in presentation section along with deck. Should I add it somewhere else as well?
