### ISSUE TITLE
Create section for Image Hub logo Layer5 Brand page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/image-hub#15]
**Current Behavior**
Image Hub logos are not available on the [Layer5 brand](https://layer5.io/brand) site.

**Desired Behavior**
A new section should be created for the Image Hub.

**Resources**
- [image-hub-logos.zip](https://github.com/layer5io/image-hub/files/4711705/image-hub-logos.zip)

**Comment by shivaylamba** [comment]
@leecalcote I would like to take this up

**Comment by leecalcote** [comment]
Thank you, sir. Yes, please, @shivaylamba

**Comment by leecalcote** [comment]
@shivaylamba it'd be good if we can tie this one off today.

**Comment by leecalcote** [comment]
Related request - https://github.com/layer5io/layer5/issues/448
