### ISSUE TITLE
Add GitHub workflow and actions for building and pushing Docker images

### ISSUE THREAD

**Issue by leecalcote** [layer5io/image-hub#3]
A new sample app has been created and is being used for presentation at DockerCon 2020. Image Hub needs a simple workflow for building and pushing it to DockerHub.

The docker login credentials are available as secrets in this repo. They can be referenced in the GitHub workflow as environment variables.

Secrets present and available to use:
- `DOCKER_USERNAME`
- `DOCKER_PASSWORD`
- `DOCKERHUB_REPOSITORY`
- `IMAGE_NAME`

**Comment by naturalett** [comment]
I will be looking into it
