### ISSUE TITLE
Relocate Whitespace and Tabs for Welcome bot 

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/image-hub#38]
**Current Behavior**
The offset request code for welcome bot isn’t in the right line slock.

**Desired Behavior**
- Move the code in line 50 & 51 to line 22 of the [.github/config.yml](https://github.com/layer5io/image-hub/blob/master/.github/config.yml)
- Clear the spacing in 45 & 46
- Edit typo “if you have yet to do so” to `“if you are yet to do so”`

---
**Resources**

**Alternatives / Additional Context**

**Comment by PluckyPrecious** [comment]
Hello @anuragsati here’s one you could get started with.😊

**Comment by geraldmaboshe** [comment]
Hey @PluckyPrecious , I would like to take up this

**Comment by PluckyPrecious** [comment]
Sure @geraldmaboshe do go ahead.
