### ISSUE TITLE
Add Slack notifier for GitHub stars on image hub

### ISSUE THREAD

**Issue by leecalcote** [layer5io/image-hub#4]
**Current Behavior**
Let the community know when people "like" their work.

**Comment by leecalcote** [comment]
Added `SLACK_BOT_TOKEN` as a repo secret.

**Comment by naturalett** [comment]
Shall I PR like we had here: https://github.com/layer5io/meshery/pull/1104 ?
@leecalcote

**Comment by leecalcote** [comment]
@naturalett please, that would be great.
