### ISSUE TITLE
[README] Update README Community Section

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/image-hub#53]
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
![img](https://user-images.githubusercontent.com/62384659/117368468-7cbfe400-aebb-11eb-92c2-0033fd74bcfc.png)
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

**Comment by leecalcote** [comment]
Thank you, @josephmidura. Notice the slight tweak in language used in this example - https://github.com/layer5io/layer5-repo-template/commit/d8c198880728a2f86ef6d81c2898e54ab1895c6a

**Comment by josephmidura** [comment]
Thanks for the heads up!
