### ISSUE TITLE
[README] Need to fix Slack badge

### ISSUE THREAD

**Issue by amino19** [layer5io/image-hub#62]
**Description**

<a href="https://github.com/layer5io/image-hub/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. For attractive look, we added some badges also.
But, there's a Slack badge failing, need to fix that. 
 
### Screenshot

**Current Behavior**

![image](https://user-images.githubusercontent.com/75872316/122434243-8d807100-cfb4-11eb-9d27-2a556131c631.png)

**Desired Behavior**
![image](https://user-images.githubusercontent.com/75872316/122434111-6fb30c00-cfb4-11eb-802c-da8745c47585.png)

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

**Comment by debjani1413** [comment]
@amino19 I would like to work on this issue.

**Comment by amino19** [comment]
@debjani1413 : Sure, pl go ahead! :slightly_smiling_face:
