### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/image-hub#97]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Resources**

**Alternatives / Additional Context**

**Comment by depleur** [comment]
Hey, I think I can fix this.

**Comment by thisiskaransgit** [comment]
@depleur, sure go ahead 🚀

**Comment by depleur** [comment]
Hey, I can't seem to find a Figma reference in this codebase.

**Comment by thisiskaransgit** [comment]
@depleur, add a new line for it please.

**Comment by abhijeetgauravm** [comment]
I want to work on it. Can u assign me?

**Comment by abhijeetgauravm** [comment]
@thisiskaransgit can i work?

**Comment by thisiskaransgit** [comment]
@abhijeetgauravm, go ahead
